[package]
name = "c"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "c_safetensors"
crate-type = ["cdylib"]      # Creates dynamic lib

[dependencies]
safetensors = { path = "../../safetensors" }

